# Generated by Django 4.0.4 on 2022-04-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=40, null=True)),
                ('nom', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('Date_adhesion', models.DateField(null=True)),
                ('chef_department', models.BooleanField(default=False)),
            ],
        ),
    ]
